/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GangStaking__factory } from "./GangStaking__factory";
export { IToken__factory } from "./IToken__factory";
