/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stader from "./stader";
export type { stader };
import type * as venus from "./venus";
export type { venus };
export type { IBEP20 } from "./IBEP20";
export type { IERC7007 } from "./IERC7007";
export type { IERC7007Enumerable } from "./IERC7007Enumerable";
export type { IERC7007Updatable } from "./IERC7007Updatable";
export type { IVerifier } from "./IVerifier";
