/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBnbX__factory } from "./IBnbX__factory";
export { IStaderStakeManager__factory } from "./IStaderStakeManager__factory";
