/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gangStakingSol from "./GangStaking.sol";
export type { gangStakingSol };
import type * as gangStakingForMerlinSol from "./GangStakingForMerlin.sol";
export type { gangStakingForMerlinSol };
import type * as gangStakingV2Sol from "./GangStakingV2.sol";
export type { gangStakingV2Sol };
import type * as core from "./core";
export type { core };
import type * as interface from "./interface";
export type { interface };
import type * as lib from "./lib";
export type { lib };
import type * as mock from "./mock";
export type { mock };
export type { AIME } from "./AIME";
export type { Lock } from "./Lock";
