/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVenusToken } from "./IVenusToken";
export type { VenusTokenInterface } from "./VenusTokenInterface";
