/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GangStakingV2__factory } from "./GangStakingV2__factory";
export { IToken__factory } from "./IToken__factory";
