/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GangStakingForMerlin__factory } from "./GangStakingForMerlin__factory";
export { IToken__factory } from "./IToken__factory";
